### ISSUE TITLE
Any simple way to Unsubscribe?

### ISSUE THREAD

**Issue by yangmingxian** [dmitry-ivashenko/eventify#1]
Now the method can be: 
```
var disposable = UiEvent.Test.Subscribe(Listen);
disposable.Dispose();
```
what we want is just a similar line,  no need to declare a new variable (disposable):
```
UiEvent.Test.Subscribe(Listen);
UiEvent.Test.Unsubscribe(Listen);
```
Is this way a right method for Unsubscribe?
`UiEvent.Test.Subscribe(Listen).Dispose();`
I think this method is to subscribe a second time and remove the 2nd one from the subscription list.

**Comment by dmitry-ivashenko** [comment]
Unfortunately, that approach won't work. An explicit disposable is necessary for unsubscribing from messages.

Imagine you have coins in a game. Every time the number of coins changes, a `UiEvent.CoinsChanged` event occurs. In the lobby, you have a header that always displays the current number of coins (the header subscribes to `UiEvent.CoinsChanged`). You also have a bank window that can be opened and closed. This window also displays the current coin count and subscribes and unsubscribes to `UiEvent.CoinsChanged`.

If there were only one `UiEvent.CoinsChanged.Unsubscribe()` method, closing the bank window would break the header's subscription because it would unsubscribe all listeners at once.

**Comment by yangmingxian** [comment]
First of all, thank you for replying to me so quickly and thoroughly.
So let me continue with the example you mentioned:
  For example, there are two subscribers to `UiEvent.CoinsChanged`: 1. `HeaderUpdate `2. `BankCoinsUpdate`
The effect I want to use is:
  `UiEvent.CoinsChanged.Unsubscribe(HeaderUpdate)`
Here I specify that the parameter is the listener function(`HeaderUpdate`), which will only close a specific subscription function rather than all listeners of the entire CoinsChanged. `BankCoinsUpdate` still works fine.

**Comment by dmitry-ivashenko** [comment]
I see what you mean. Let me demonstrate an example from a real project:

```
public void OnEnable()
{
  _disposable = new CompositeDisposable
  {
    NetGlobalEvent.PlayerReady.Subscribe<PlayerReadyData>(OnPlayerReady),
    SyncEvent.BattleUnitsReady.Subscribe<List<BattleUnit>>(OnBattleUnitsReady),
    NetGlobalEvent.RoundStarted.Subscribe<PlayerStartRoundData>(OnRoundStarted),
    UiEvent.FinishIntro.Subscribe(() => _isBattleIntroFinished = true),
    NetPlayerEvent.RoundFinished.Subscribe<PlayerEndRoundData>(OnRoundFinished),
    DebugEvent.WinFight.Subscribe(() => FinishBattle(WinnerType.Blue)),
    DebugEvent.LoseFight.Subscribe(() => FinishBattle(WinnerType.Red)),
    DebugEvent.DrawFight.Subscribe(() => FinishBattle(WinnerType.Nobody)),
    DebugEvent.WindRound.Subscribe(WinRound),
    SyncEvent.BattleReset.Subscribe(OnBattleReset),
    NetPlayerEvent.BattleFinish.Subscribe<PlayerBattleFinishData>(OnBattleFinish),
  };
}

public void OnDisable()
{
  _disposable.Dispose();
}
```

This is roughly the same pattern seen in every window, manager or controller. Here you can see that if we replace Disposable with internal link counting (Subscribe/Unsubscribe), there are 2 important changes:

- we will no longer be able to use anonymous functions to subscribe to events (` UiEvent.FinishIntro.Subscribe(() => _isBattleIntroFinished = true)`), i.e. there will be more code to write
- OnDisable method will require as much code as OnEnable method to Unsubscribe every subscription, i.e. there will be even more code to write

**Comment by yangmingxian** [comment]
I think I get it, your approach has more flexibility as a result.
If I want to unsubscribe from certain functions, I only need to place these functions separately in another CompositeDisposable, and then manually Dispose() it, like the following example:
 ```
         // Need to manually Unsubscription
         var _disposableManually = new CompositeDisposable
         {
             UiEvent.Event1.Subscribe(Func1),
             UiEvent.Event1.Subscribe(Func2),
             UiEvent.Event3.Subscribe(() => testBool = true)
         };

         // Don’t want to Unsubscription
         var _disposableOndisable = new CompositeDisposable
         {
             UiEvent.Event6.Subscribe(Func4),
             UiEvent.Event4.Subscribe(Func2),
         };

         //Add one more to the manually unsubscribed list
         _disposableManually.Add(UiEvent.Event7.Subscribe(Func1));

         // Unsubscribe from the above 4 events
         _disposableManually.Dispose();
```
If I want to unsubscribe in different places and conditions, I just declare more CompositeDisposable and Dispose() them in the right place. Also: if I subscribe to some function in one class and I want to unsubscribe it in another class, I need to pass this disposable variable into that class.

**Comment by dmitry-ivashenko** [comment]
Thank you for your thorough and well-considered comments. Your suggestion about providing a way to unsubscribe from a specific event by passing the handler function is an interesting one.

Your approach of using different CompositeDisposable instances to manage subscriptions that you want to unsubscribe from separately is indeed one way to go about it. This provides the flexibility to dispose of specific groups of subscriptions as needed.

However, it's worth mentioning that our original design choice for requiring an explicit disposable was not just for the sake of flexibility but also for greater code safety. By using disposables, you make the unsubscribing process more explicit and less prone to errors, like accidentally unsubscribing the wrong handler. It also integrates better with frameworks that use the IDisposable pattern.

As for passing the disposable between different classes, that approach can work but it does couple the classes more tightly. If you find yourself needing to pass disposables around frequently, it may be worth re-evaluating your design choices to see if there's a way to manage subscriptions more centrally.

That said, your feedback has given me something to think about, and I'll definitely consider this feature for a future release. Thank you for contributing to the discussion!

**Comment by yangmingxian** [comment]
Thank you for your open-source project, It is the most complete and robust event system I have seen recently. This is a rare and good project for developers. Thank you for your code and your patient replies.
